version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.2
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Create page
          command: npm start
      - run:
          name: Post to gh-pages
          command: curl ci-cd.net/v1/gh/pages | bash -s docs/.
      - run:
          name: CloufFlare - Purge everything
          command: |
            curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${CF_ZONE}/purge_cache" \
             -H "X-Auth-Email: ${CF_EMAIL}" \
             -H "X-Auth-Key: ${CF_API_KEY}" \
             -H "Content-Type: application/json" \
             --data '{"purge_everything":true}'
workflows:
  version: 2
  website:
    jobs:
      - build:
          context: globalenv
          filters:
            branches:
              only:
                - master
